# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 6166eaa
_src_path: gh:42WASD/template-docs-project
author: jya0
org: 42WASD
project_name: ubuntu-server-iac
project_slug: ubuntu-server-iac
