apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meme-site
  namespace: dev-42wasd-admin
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: meme.alpha.taild82ced.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meme-site
                port:
                  number: 80