apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-budget
  namespace: dev-jya0
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "8"
    requests.memory: 8Gi
    limits.memory: 16Gi
    requests.ephemeral-storage: 20Gi
    limits.ephemeral-storage: 40Gi
    requests.storage: 150Gi
    pods: "40"
    services: "15"
    persistentvolumeclaims: "10"
    configmaps: "50"
    secrets: "30"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-budget
  namespace: prd-jya0
spec:
  hard:
    requests.cpu: "8"
    limits.cpu: "12"
    requests.memory: 16Gi
    limits.memory: 24Gi
    requests.ephemeral-storage: 30Gi
    limits.ephemeral-storage: 60Gi
    requests.storage: 300Gi
    pods: "60"
    services: "20"
    persistentvolumeclaims: "15"
    configmaps: "80"
    secrets: "50"