apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-budget
  namespace: mlops
spec:
  hard:
    requests.cpu: "8"
    limits.cpu: "16"
    requests.memory: 16Gi
    limits.memory: 32Gi
    requests.ephemeral-storage: 60Gi
    limits.ephemeral-storage: 120Gi
    requests.storage: 500Gi
    requests.nvidia.com/gpu: "1"
    pods: "60"
    services: "20"
    persistentvolumeclaims: "20"
    configmaps: "80"
    secrets: "50"