apiVersion: v1
kind: LimitRange
metadata:
  name: container-defaults
  namespace: mlops
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 500m
        memory: 1Gi
        ephemeral-storage: 2Gi
      default:
        cpu: "4"
        memory: 8Gi
        ephemeral-storage: 8Gi
      max:
        cpu: "16"
        memory: 32Gi
        ephemeral-storage: 60Gi