apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-test
  namespace: dev-42wasd-admin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme-fast
  resources:
    requests:
      storage: 2Gi