apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-test-retain
  namespace: dev-42wasd-admin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme-db
  resources:
    requests:
      storage: 1Gi